### ISSUE TITLE
Domain modules are not injected

### ISSUE THREAD

**Issue by sarnakov** [HowProgrammingWorks/NodejsStarterKit#127]
For example: Seems like `resmon` is not injected.
Stack trace:
```
/api/resmon - TypeError: Cannot read property 'getStatistics' of undefined
    at Object.method (/api/resmon.js:3:36)
    at Client.rpc (/lib/client.js:77:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) - 500
```

**Comment by tshemsedinov** [comment]
@sarnakov Fixed, thanks for reporting this!
